site_name: ExNihilo Bedrock Wiki
remote_branch: wiki
repo_url: https://github.com/PrograMistV1/ExNihilo_Bedrock
site_url: https://www.curseforge.com/minecraft-bedrock/addons/exnihilo-bedrock
edit_uri: ""
site_author: PrograMistV1
use_directory_urls: false
theme:
  name: readthedocs
  analytics:
    gtag: G-BYLVMYGMTX

nav:
  - Home: index.md
  - Getting Started:
      - Basics: getting-started/index.md
  - Blocks:
      - Introduction: blocks/index.md
      - Barrel: blocks/barrel.md
      - Sieve: blocks/sieve.md
      - Crucible: blocks/crucible.md
  - Items:
      - Introduction: items/index.md
      - Crooks: items/crook.md
      - Hammers: items/hammer.md

extra_css:
  - css/crafting.css
extra_javascript:
  - javascripts/crafting.js
plugins:
  - macros